apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
        - name: node-container
          image: my-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort              # ⭐ YEH ADD KARO (tumne miss kiya tha)
  selector:
    app: my-node
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
---
apiVersion: autoscaling/v2      # ⭐ v1 ki jagah autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-node-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50