apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app          # Deployment ka naam (jo marzi do)
spec:
  replicas: 2                # Starting mein 2 pods
  selector:
    matchLabels:
      app: my-node           # Label jo pods pe hoga
  template:                  # Pod ka template
    metadata:
      labels:
        app: my-node         # ⭐ Same label (selector match karega)
    spec:
      containers:
      - name: node-container # Container ka naam (kuch bhi)
        image: my-app:v1     # ⭐ Docker image ka naam
        imagePullPolicy: Never  # Local image use karo
        ports:
        - containerPort: 4000   # App ka port
        resources:
          limits:
            cpu: "200m"      # Max CPU per pod
            memory: "256Mi"  # Max RAM per pod
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: my-node
  ports:
  - port: 4000   # ⭐ Service ka port (bahar se isse access hoga)
    targetPort: 4000
    nodePort: 30001
---
apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
    name: my-node-hpa          # HPA ka naam
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-node-app        # ⭐ Deployment ka naam (Block 1 se)
  minReplicas: 2             # Minimum pods
  maxReplicas: 10            # Maximum pods (10×100=1000 users)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # 50% CPU pe naya pod